# Generated by Django 3.2.25 on 2025-06-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='user_profile',
        ),
    ]
